/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tirthal.learning.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the NewsEntry service. Represents a row in the &quot;SB_NEWS_NewsEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.tirthal.learning.model.impl.NewsEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.tirthal.learning.model.impl.NewsEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NewsEntry
 * @see com.tirthal.learning.model.impl.NewsEntryImpl
 * @see com.tirthal.learning.model.impl.NewsEntryModelImpl
 * @generated
 */
@ProviderType
public interface NewsEntryModel extends BaseModel<NewsEntry>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a news entry model instance should use the {@link NewsEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this news entry.
	 *
	 * @return the primary key of this news entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this news entry.
	 *
	 * @param primaryKey the primary key of this news entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this news entry.
	 *
	 * @return the uuid of this news entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this news entry.
	 *
	 * @param uuid the uuid of this news entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the news ID of this news entry.
	 *
	 * @return the news ID of this news entry
	 */
	public long getNewsId();

	/**
	 * Sets the news ID of this news entry.
	 *
	 * @param newsId the news ID of this news entry
	 */
	public void setNewsId(long newsId);

	/**
	 * Returns the group ID of this news entry.
	 *
	 * @return the group ID of this news entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this news entry.
	 *
	 * @param groupId the group ID of this news entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this news entry.
	 *
	 * @return the company ID of this news entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this news entry.
	 *
	 * @param companyId the company ID of this news entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this news entry.
	 *
	 * @return the user ID of this news entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this news entry.
	 *
	 * @param userId the user ID of this news entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this news entry.
	 *
	 * @return the user uuid of this news entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this news entry.
	 *
	 * @param userUuid the user uuid of this news entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this news entry.
	 *
	 * @return the user name of this news entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this news entry.
	 *
	 * @param userName the user name of this news entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this news entry.
	 *
	 * @return the create date of this news entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this news entry.
	 *
	 * @param createDate the create date of this news entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this news entry.
	 *
	 * @return the modified date of this news entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this news entry.
	 *
	 * @param modifiedDate the modified date of this news entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this news entry.
	 *
	 * @return the title of this news entry
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this news entry.
	 *
	 * @param title the title of this news entry
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this news entry.
	 *
	 * @return the description of this news entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this news entry.
	 *
	 * @param description the description of this news entry
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(NewsEntry newsEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<NewsEntry> toCacheModel();

	@Override
	public NewsEntry toEscapedModel();

	@Override
	public NewsEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}